name: pyFreeze
version: '${project.version}'
main: org.me.pyke.pyfreeze.PyFreeze
api-version: '1.20'
author: 666pyke
commands:
  pyfreeze:
    description: Freeze or unfreeze a player, or reload the plugin.
    permission: pyfreeze.use
    aliases: [freeze]
    permission-message: "§8「§cFreeze§8」§7» §fRunning §cpyFreeze ${project.version} §fby §7666pyke"